# Generated by Django 5.1.6 on 2025-02-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('birthdate', models.DateField()),
                ('department', models.CharField(choices=[('CE', 'computer'), ('IT', 'informtion tech'), ('CL', 'civil'), ('EC', 'electronic'), ('MH', 'machanicle'), ('CH', 'chemicle')], max_length=2)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('semester', models.DecimalField(decimal_places=0, max_digits=8)),
                ('about', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
